print ("Hello, this is Olga.")
print ("Hello, this is Tatjana.")
print("Hello, this is Inese")
print ("Hello, this is Greta.")
print ("Hello, this is Vlada!")
print("Hi, this is Kristiana!")
print ("Hello, this is Ieva")
print("Hello, this is LauraZ")
print ("Hello, this is Marta!")
print ("Hello, this is Inga")
print("Hello, this is Ieva P")
print("Hello, this is Indre")
print("Hello, this is Anete S")
print("Hello, this is Monika Ras")
print("Hello, ths is Jolanta")